-- MS SQL solutions:
--Solution 1:
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE SALARY IN (
    SELECT MAX(E1.SALARY)
    FROM EMPLOYEE E1
    WHERE E.DEPARTMENTID = E1.DEPARTMENTID
    )  

--Solution 2:
WITH MAXSALARYDEPT 
AS
    (
       SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANKSLRY
       FROM EMPLOYEE E
       INNER JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
    )

SELECT DEPARTMENT,EMPLOYEE,SALARY 
FROM MAXSALARYDEPT
WHERE RANKSLRY = 1


-- Postgre SQL and MySQL Solution: 
# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE (E.DEPARTMENTID, E.SALARY) IN (
    SELECT DEPARTMENTID, MAX(SALARY)
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID);

