-- MS SQL 

-- Solution 1:
SELECT (SELECT DISTINCT SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY) AS SecondHighestSalary

-- Solution 2:
SELECT MAX(SALARY) AS SecondHighestSalary
FROM EMPLOYEE
WHERE SALARY != (SELECT MAX(SALARY) FROM EMPLOYEE) 